import time
import csv


#This file implements a hash table with chaining and runs the experiment to 
#measure the average number of probes and time taken for insertions, successful 
#searches, and unsuccessful searches. It reads the keys from the CSV files generated by keys.py.

class Node:
    def __init__(self, key, value):
        self.key = key
        self.value = value
        self.next = None

class HashTableChaining:
    def __init__(self, capacity):
        self.capacity = capacity
        self.size = 0
        self.table = [None] * capacity

    def _hash(self, key):
        return hash(key) % self.capacity

    def insert(self, key, value):
        index = self._hash(key)
        probes = 1  # bucket access

        current = self.table[index]
        while current:
            probes += 1
            if current.key == key:
                current.value = value
                return probes
            current = current.next

        new_node = Node(key, value)
        new_node.next = self.table[index]
        self.table[index] = new_node
        self.size += 1
        return probes

    def search(self, key):
        index = self._hash(key)
        probes = 1  # bucket access

        current = self.table[index]
        while current:
            probes += 1
            if current.key == key:
                return True, probes
            current = current.next

        return False, probes

# Run the experiment for different load factors
m = 100000
alphas = [0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]  
results = []

def run_experiment(alpha):
    n = int(alpha * m)
    ht = HashTableChaining(m)

    # Read keys from CSV files
    with open(f"insert_{alpha}.csv", "r") as f:
        insert_keys = [int(row[0]) for row in csv.reader(f)]

    with open(f"unsuccessful_{alpha}.csv", "r") as f:
        unsuccessful_keys = [int(row[0]) for row in csv.reader(f)]

    # Measure insertions
    total_probes_insert = 0
    start_time = time.time()
    for key in insert_keys:
        total_probes_insert += ht.insert(key, key)
    end_time = time.time()
    avg_probes_insert = total_probes_insert / n
    time_insert = end_time - start_time

    # Measure successful searches
    total_probes_successful = 0
    start_time = time.time()
    for key in insert_keys:
        _, probes = ht.search(key)
        total_probes_successful += probes
    end_time = time.time()
    avg_probes_successful = total_probes_successful / n
    time_successful = end_time - start_time

    # Measure unsuccessful searches
    total_probes_unsuccessful = 0
    start_time = time.time()
    for key in unsuccessful_keys:
        _, probes = ht.search(key)
        total_probes_unsuccessful += probes
    end_time = time.time()
    avg_probes_unsuccessful = total_probes_unsuccessful / n
    time_unsuccessful = end_time - start_time

    return (alpha,
        avg_probes_insert, time_insert,
        avg_probes_successful, time_successful,
        avg_probes_unsuccessful, time_unsuccessful)

# Run the experiment for each load factor
results = []

for alpha in alphas:
    results.append(run_experiment(alpha))

# Write results to CSV file
with open("chaining_results.csv", "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["Load Factor", "Avg Probes Insert", "Time Insert", "Avg Probes Successful Search", "Time Successful Search", "Avg Probes Unsuccessful Search", "Time Unsuccessful Search"])
    w.writerows(results)
