import time, csv

# This file implements a hash table with linear probing and runs 
# the experiment to measure the average number of probes and time 
# taken for insertions, successful searches, and unsuccessful searches. 
# It reads the keys from the CSV files generated by keys.py.

class HashTableLinearProbing:
    def __init__(self, size):
        self.size = size
        self.table = [None] * size

    def _hash(self, key):
        return hash(key) % self.size
    
    # isert a key-value pair into the hash table
    # return the number of probes
    def insert(self, key):
        i = self._hash(key)
        probes = 1

        while self.table[i] is not None:
            probes += 1
            if self.table[i] == key:
                return probes  # key already exists
            i = (i + 1) % self.size
        
        probes += 1 # for the final insertion
        self.table[i] = key
        return probes   
    
    # search for a key
    # returns a tuple (found, probes) 
    def search(self, key):
        i = self._hash(key)
        probes = 1

        while self.table[i] is not None:
            probes += 1
            if self.table[i] == key:
                return True, probes
            i = (i + 1) % self.size
        
        probes += 1 # for the final unsuccessful search
        return False, probes
    
# Run the experiment for different load factors
m = 100000
alphas = [0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]

def run_experiment(alpha):
    ht = HashTableLinearProbing(m)

    with open(f"insert_{alpha}.csv", "r") as f:
        insert_keys = [int(row[0]) for row in csv.reader(f)]
    with open(f"unsuccessful_{alpha}.csv", "r") as f:
        unsuccessful_keys = [int(row[0]) for row in csv.reader(f)]
    
    n = len(insert_keys)

    # Measure insertions
    total_probes_insert = 0
    start_time = time.time()
    for key in insert_keys:
        total_probes_insert += ht.insert(key)
    end_time = time.time()
    avg_probes_insert = total_probes_insert / n
    time_insert = end_time - start_time

    # Measure successful searches
    total_probes_successful = 0
    start_time = time.time()
    for key in insert_keys:
        _, probes = ht.search(key)
        total_probes_successful += probes
    end_time = time.time()
    avg_probes_successful = total_probes_successful / n
    time_successful = end_time - start_time

    # Measure unsuccessful searches
    total_probes_unsuccessful = 0
    start_time = time.time()
    for key in unsuccessful_keys:
        _, probes = ht.search(key)
        total_probes_unsuccessful += probes 
    end_time = time.time()
    avg_probes_unsuccessful = total_probes_unsuccessful / n
    time_unsuccessful = end_time - start_time
    return (alpha, avg_probes_insert, time_insert, avg_probes_successful, time_successful, avg_probes_unsuccessful, time_unsuccessful)

results = []
for alpha in alphas:
    results.append(run_experiment(alpha))

with open("linear_probing_results.csv", "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["Load Factor", "Avg Probes Insert", "Time Insert", "Avg Probes Successful Search", "Time Successful Search", "Avg Probes Unsuccessful Search", "Time Unsuccessful Search"])
    for result in results:
        w.writerow(result)
